#!/bin/sh
# /etc/nginx/geoip_update.sh
# Update GeoIP proxy list to the current list of cloudflare IP addresses

outfile=$(dirname "$0")/geoip_cloudflare.conf

echo "# Auto-generated by $0" > "$outfile"

# Get IPv4 and IPv6 addresses for Cloudflare
ipv4=$(curl -s https://www.cloudflare.com/ips-v4)
ipv6=$(curl -s https://www.cloudflare.com/ips-v6)

echo "$ipv4" | while read ip; do
  echo "geoip2_proxy $ip;" >> geoip_cloudflare.conf
done

echo "$ipv6" | while read ip; do
  echo "geoip2_proxy $ip;" >> geoip_cloudflare.conf
done